import * as vscode from "vscode";
import type { HappyDocsConfig } from "./types";

const defaults: HappyDocsConfig = {
  include: [
    "src/**/*.{ts,tsx,js,jsx}",
    "app/**/*.{ts,tsx,js,jsx}",
    "routes/**/*.{ts,tsx,js,jsx}",
    "controllers/**/*.{ts,tsx,js,jsx}"
  ],
  exclude: [
    "**/node_modules/**",
    "**/dist/**",
    "**/build/**",
    "**/coverage/**",
    "**/*.test.*",
    "**/*.spec.*",
    "**/*.generated.*"
  ],
  frameworks: ["express", "nestjs"],
  outputDirectory: "docs/api",
  openapiFormat: "yaml",
  apiTitle: "My API",
  apiVersion: "1.0.0",
  apiDescription: "API documentation generated by HappyDocs.",
  baseUrl: "http://localhost:3000",
  enableAiEnrichment: false,
  aiProvider: "openai",
  maxFiles: 2500
};

export function getConfig(resource?: vscode.Uri): HappyDocsConfig {
  const value = vscode.workspace.getConfiguration("hybridApiDocs", resource);
  return {
    include: value.get<string[]>("include", defaults.include),
    exclude: [...new Set([...defaults.exclude, ...value.get<string[]>("exclude", [])])],
    frameworks: value.get<HappyDocsConfig["frameworks"]>("frameworks", defaults.frameworks),
    outputDirectory: value.get<string>("outputDirectory", defaults.outputDirectory),
    openapiFormat: value.get<HappyDocsConfig["openapiFormat"]>(
      "openapiFormat",
      defaults.openapiFormat
    ),
    apiTitle: value.get<string>("apiTitle", defaults.apiTitle),
    apiVersion: value.get<string>("apiVersion", defaults.apiVersion),
    apiDescription: value.get<string>("apiDescription", defaults.apiDescription),
    baseUrl: value.get<string>("baseUrl", defaults.baseUrl),
    enableAiEnrichment: value.get<boolean>("enableAiEnrichment", defaults.enableAiEnrichment),
    aiProvider: value.get<"openai">("aiProvider", defaults.aiProvider),
    maxFiles: value.get<number>("maxFiles", defaults.maxFiles)
  };
}
